config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :people
  resources :pledge_classes
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true

  belongs_to :pledge_class

  def full_name
    first_name + " " + pledge_name + " " + last_name
  end

end

app/models/pledge_class.rb
class PledgeClass < ActiveRecord::Base
  validates :name, presence: true
  validates :semester, presence: true
  validates :year, presence: true

  has_many :people

  def term
    semester + " " + year.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all

    respond_to do |format|
      format.html
      format.json { render json: @people }
    end
  end

  def new
    @person = Person.new

    respond_to do |format|
      format.html
      format.json { render json: @person }
    end
  end


  def create
    @person = Person.new(person_params)

    @person.save
    redirect_to new_person_path
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :pledge_name)
  end
end

app/controllers/pledge_classes_controller.rb
class PledgeClassesController < ApplicationController

  def index
    @pledge_classes = PledgeClass.all

    respond_to do |format|
      format.html
      format.json { render json: @pledge_classes }
    end
  end

  def new
    @pledge_class = PledgeClass.new

    respond_to do |format|
      format.html
      format.json { render json: @pledge_class }
    end
  end

  def create
    @pledge_class = PledgeClass.new(pledge_class_params)

    @pledge_class.save
    redirect_to new_pledge_class_path
  end

  private

  def pledge_class_params
    params.require(:pledge_class).permit(:name, :semester, :year)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pledge_classes_helper.rb
module PledgeClassesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sigma Chi Delta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<h1>Listing all People</h1>

<%= link_to('Create new person', new_person_path) %>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
  <% @people.each do |person| %>
    <tr>
      <td>
        <%= person.full_name %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= link_to('See all people', people_path) %>

<%= form_for @person do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :pledge_name %><br>
    <%= f.text_field :pledge_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p> 

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pledge_classes/index.html.erb
<h1>Listing all pledge classes</h1>

<%= link_to('Create new pledge class', new_pledge_class_path) %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Term</th>
    </tr>
  </thead>
  <tbody>
    <% @pledge_classes.each do |pledge_class| %>
      <tr>
        <td>
          <%= pledge_class.name %>
        </td>
        <td>
          <%= pledge_class.term %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pledge_classes/new.html.erb
<h1>New Pledge Class</h1>

<%= link_to('See all pledge classes', pledge_classes_path) %>

<%= form_for @pledge_class do |f| %>
  <p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  </p>

  <p>
  <%= f.label :semester %><br>
  <%= f.text_field :semester %>
  </p>

  <p>
  <%= f.label :year %><br>
  <%= f.text_field :year %>
  </p>

  <p>
  <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to your very first Rails app</h1>
<p>Now it's up to you to customize it!</p>